### ISSUE TITLE
adding/subtracting an integer to/from a HebrewDate does not increment/decrement year

### ISSUE THREAD

**Issue by hudcap** [simlist/pyluach#10]
MWE:

    from pyluach import dates
    
    dates.HebrewDate(5782, 1, 1) - 1
    dates.HebrewDate(5782, 13, 29) + 1

returns:

    HebrewDate(5782, 13, 29)
    HebrewDate(5782, 1, 1)

**Comment by simlist** [comment]
The months are numbered as 1 for Nissan through 13 for Adar Beis but the year changes over on the first of Tishrei so that is expected. Try `HebrewDate(5782, 6, 29) + 1` and you should see the year increment.

**Comment by hudcap** [comment]
Of course! So sorry -- my bad!
