### ISSUE TITLE
New API - `fast`

### ISSUE THREAD

**Issue by aviadlevy** [simlist/pyluach#11]
I want to automatically congrats on holiday, but the blessing is different between  fast and actual holiday.

We can do it without inflecting the current `holiday` API that still will return fast alongside holiday.

**Comment by simlist** [comment]
I don't think it makes sense to only separate out fast days without also making a separate method for non fast day holidays. I'll need to think of a name that would work as holiday is already taken. Maybe festival of chag.

**Comment by aviadlevy** [comment]
Agreed. I didn't want to touch the current `holiday` method from obvious reasons.  
When you think of something, let me know and I'll update my PR

**Comment by simlist** [comment]
I'm just curious, in your use case would you want Yom Kippur returned under fast days?

**Comment by aviadlevy** [comment]
It's tricky indeed, but I think Yom Kippur should be a holiday.  
(even the blessing for Yom Kippur is חג שמח)

**Comment by simlist** [comment]
That was my thinking too.

**Comment by simlist** [comment]
Implemented in v1.2.0. [https://github.com/simlist/pyluach/compare/v1.1.1...v1.2.0](url)
