### ISSUE TITLE
pip install pylauch broken

### ISSUE THREAD

**Issue by max4211** [simlist/pyluach#28]
Following the instructions on https://pypi.org/project/pyluach/, but am unable to install the library using pip or pip3. Was it delisted from pypi?

> pip3 install pylauch
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement pylauch (from versions: none)
ERROR: No matching distribution found for pylauch                                                                                                                    

> pip install pylauch
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement pylauch (from versions: none)
ERROR: No matching distribution found for pylauch

> pip --version
pip 23.2.1 from /usr/local/lib/python3.10/dist-packages/pip (python 3.10)

> pip3 --version
pip 23.2.1 from /usr/local/lib/python3.10/dist-packages/pip (python 3.10)

**Comment by simlist** [comment]
Make sure you spell it `pyluach` not `pylauch`.
