### ISSUE TITLE
Official release?

### ISSUE THREAD

**Issue by mwarkentin** [simlist/pyluach#3]
Hello,

I was just wondering if there are any plans to publish an "official" (non-dev) release of this package? One of our dependencies started pulling in `pyluach` as a sub-dependency in a new release, and with our package management tool (`pipenv`) we either need to specify `--pre` to get it to work (which can then pull in other pre-release packages which we don't want, or pin our dependency to an older version.

Thanks!

**Comment by simlist** [comment]
I  do plan on publishing an official release but I don't know when I'll have a chance. I'm not planning on changing much in the api; mostly just better testing. I will try to prioritize this project to get that done.

**Comment by mwarkentin** [comment]
Thanks, we’d appreciate it!

**Comment by simlist** [comment]
Official release 1.0.1 is out! Sorry about the delay.
