### ISSUE TITLE
holiday support

### ISSUE THREAD

**Issue by ofir1023** [simlist/pyluach#5]
I would like to have holiday support in this project.
The basic support is that if holiday=True, getparash will return the closest parasha or holiday, plus to add the hol-hamo'ed parashos to all parashos. 
I don't mind contribute it myself, but first I would like to discuss the design with you.

**Comment by simlist** [comment]
What do you mean Chol Hamoed Parshios? Do you mean the special Torah reading for each day of the holidays?

**Comment by ofir1023** [comment]
I meant adding "Hol-hamo'ed Sukot" (and the same for passover) parasha to the parshios list, and return it on the shabbos of  hol-hamo'ed.

**Comment by ofir1023** [comment]
The way I see it, if you did getparasha (with holiday=True) today (Tuesday of Hol-hamo'ed) you would get "Hol-hamo'ed Sukot", and if you did it on Sunday you would get just 'Sukot' (since that's the closest)

**Comment by simlist** [comment]
Do you mean returning the holiday of the following Shabbos or of the day of the week given if it's a holiday?

**Comment by ofir1023** [comment]
yes. it will just add to the parashos pool also holidays (rosh ha'shana, yom kipur, sukot etc.) and holiday's shabbos.
