### ISSUE TITLE
Hebrew date start with Tishery as the first month

### ISSUE THREAD

**Issue by aviadlevy** [simlist/pyluach#6]
When requested (with a flag or by another class), we set the Hebrew date to set Tishrey as the 1st month, and Elul as the last one.  
I'm willing to start working on this feature, but first I wanted to check if it's something that you also think is useful and worth working on. I also wanted to consult with you what you think is the best approach for this feature (flag or another class).  
Let me know what you think ☺️

**Comment by simlist** [comment]
I thought about that but decided implementation would be a nightmare. How do you plan on dealing with leap years with the extra month in the middle of the year?

**Comment by aviadlevy** [comment]
One option, and the obvious one:  
* Adar A: 6  
* Adar B: 7  
* Elul: 13  

Other option (that I'm not fimiliar enough with the code to know if it's possible), is to return another variable along side the number as "extra information":  
* Adar A: 6 a  
* Adar B: 6 b  
* Elul: 12  

I think the 1st option is better, and I'm sure that the user who uses this counting will take this option into his consideration. 
  
I didn't fully dived into the code yet to estimate how nightmare it would be to implement this. That's why I asked what you think first :sunglasses:

**Comment by simlist** [comment]
I think it would not be that difficult to implement. The issue would be that for anything specific to a month like holidays or fast days, you would need to check if the year is a leap year for every month `>= 6` just to know what month it is. With Nissan as the first month you only have to check for Adar.

**Comment by aviadlevy** [comment]
Agreed, but I think that it's something the user who uses this feature will take into consideration.  
Note that anyone who want to use the current implementation for "regular" year will also need to check if `month < 7` to know what actual year is it (that's what I did in small app I wrote)
